# Generated by Django 4.2.7 on 2026-04-25 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("variety", models.CharField(blank=True, max_length=120)),
                ("season", models.CharField(blank=True, max_length=80)),
                ("sowing_date", models.DateField(blank=True, null=True)),
                ("expected_harvest_date", models.DateField(blank=True, null=True)),
                ("area_hectares", models.FloatField(default=0.0)),
                ("status", models.CharField(default="active", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("location_name", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("area_hectares", models.FloatField(default=0.0)),
                ("boundary_geojson", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=120)),
                ("mandi_name", models.CharField(max_length=150)),
                ("location", models.CharField(max_length=150)),
                ("price_per_quintal", models.FloatField()),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("source", models.CharField(default="manual", max_length=120)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="cropdiseasereport",
            name="recommended_pesticide",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="cropdiseasereport",
            name="severity",
            field=models.CharField(default="low", max_length=20),
        ),
        migrations.AddField(
            model_name="cropdiseasereport",
            name="treatment",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="YieldPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expected_harvest_tons", models.FloatField()),
                ("profit_estimate", models.FloatField()),
                ("risk_level", models.CharField(default="medium", max_length=20)),
                (
                    "model_name",
                    models.CharField(default="rule-based-baseline", max_length=80),
                ),
                ("input_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yield_predictions",
                        to="api.crop",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yield_predictions",
                        to="api.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="manual", max_length=80)),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("rainfall_mm", models.FloatField(default=0.0)),
                ("wind_speed_kmph", models.FloatField(default=0.0)),
                ("condition", models.CharField(blank=True, max_length=120)),
                ("forecast_for", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_data",
                        to="api.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoilData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("alluvial", "Alluvial Soil"),
                            ("black", "Black Soil"),
                            ("red", "Red Soil"),
                            ("laterite", "Laterite Soil"),
                            ("desert", "Desert Soil"),
                            ("mountain", "Mountain Soil"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("soil_ph", models.FloatField()),
                ("soil_moisture", models.FloatField(help_text="Percentage")),
                ("nitrogen_level", models.FloatField(help_text="mg/kg")),
                ("phosphorus_level", models.FloatField(help_text="mg/kg")),
                ("potassium_level", models.FloatField(help_text="mg/kg")),
                ("organic_matter", models.FloatField(help_text="Percentage")),
                ("soil_temperature", models.FloatField(help_text="Celsius")),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_readings",
                        to="api.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SatelliteObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="sentinel", max_length=120)),
                ("ndvi", models.FloatField(blank=True, null=True)),
                ("moisture_index", models.FloatField(blank=True, null=True)),
                ("crop_stress_score", models.FloatField(default=0.0)),
                ("drought_risk", models.CharField(default="low", max_length=20)),
                ("pest_risk", models.CharField(default="low", max_length=20)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("observed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="satellite_observations",
                        to="api.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IrrigationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommended_water_mm", models.FloatField()),
                ("recommended_time", models.DateTimeField()),
                ("irrigation_method", models.CharField(default="drip", max_length=50)),
                ("advisory", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irrigation_schedules",
                        to="api.crop",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irrigation_schedules",
                        to="api.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DigitalTwinSimulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario_name", models.CharField(max_length=150)),
                ("assumptions", models.JSONField(blank=True, default=dict)),
                ("projected_yield_change_pct", models.FloatField(default=0.0)),
                ("projected_water_change_pct", models.FloatField(default=0.0)),
                (
                    "projected_risk_level",
                    models.CharField(default="medium", max_length=20),
                ),
                ("recommendations", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_twin_runs",
                        to="api.farm",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="crop",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crops",
                to="api.farm",
            ),
        ),
        migrations.AddField(
            model_name="cropdiseasereport",
            name="crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disease_reports",
                to="api.crop",
            ),
        ),
        migrations.AddField(
            model_name="cropdiseasereport",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disease_reports",
                to="api.farm",
            ),
        ),
    ]
