import { StyleSheet } from 'react-native';

export const colors = {
  background: '#0F172A',
  card: 'rgba(255,255,255,0.06)',
  border: 'rgba(255,255,255,0.12)',
  text: '#FFFFFF',
  muted: '#9FB7D3',
  primary: '#1B5E20',
  secondary: '#81C784',
  accent: '#FFC107',
  error: '#FEE2E2',
};

export const appStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  scrollContent: { paddingHorizontal: 16, gap: 12, paddingBottom: 90 },
  topBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14 },
  brand: { color: '#E5F5E0', fontSize: 24, fontWeight: '700' },
  brandSub: { color: '#A5D6A7', fontSize: 12, marginTop: 2 },
  topActions: { flexDirection: 'row', gap: 8 },
  topIcon: { color: '#E6EEFF', backgroundColor: 'rgba(255,255,255,0.12)', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12, fontSize: 12 },
  searchWrap: { paddingHorizontal: 16, paddingBottom: 10 },
  searchInput: { backgroundColor: 'rgba(255,255,255,0.08)', borderColor: colors.border, borderWidth: 1, borderRadius: 14, color: '#E6EEFF', paddingHorizontal: 14, paddingVertical: 10 },
  sectionCard: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 16, padding: 14 },
  sectionTitle: { color: colors.text, fontSize: 18, fontWeight: '700', marginBottom: 10 },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  metricCard: { width: '48%', backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 12, borderWidth: 1, borderColor: colors.border, padding: 10 },
  metricLabel: { color: colors.muted, fontSize: 11 },
  metricValue: { color: colors.text, fontSize: 20, fontWeight: '700', marginTop: 6 },
  metricUnit: { color: colors.muted, fontSize: 12, fontWeight: '400' },
  metricTrend: { color: colors.secondary, fontSize: 11, marginTop: 6 },
  miniMetric: { width: '48%', backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 12, padding: 10, borderWidth: 1, borderColor: colors.border },
  miniMetricLabel: { color: colors.muted, fontSize: 11 },
  miniMetricValue: { color: colors.text, fontWeight: '700', marginTop: 5 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { backgroundColor: 'rgba(255,255,255,0.08)', borderRadius: 999, paddingVertical: 7, paddingHorizontal: 10 },
  chipText: { color: '#D4E2F7', fontSize: 12 },
  primaryButton: { backgroundColor: colors.primary, borderRadius: 10, paddingVertical: 10, paddingHorizontal: 14, alignSelf: 'flex-start' },
  primaryButtonText: { color: colors.text, fontWeight: '700' },
  accentButton: { marginTop: 8, backgroundColor: colors.accent, borderRadius: 10, paddingVertical: 9, paddingHorizontal: 12, alignSelf: 'flex-start' },
  accentButtonText: { color: '#2C2C2C', fontWeight: '700' },
  insightCard: { marginTop: 12, backgroundColor: 'rgba(255,193,7,0.12)', borderColor: 'rgba(255,193,7,0.5)', borderWidth: 1, borderRadius: 12, padding: 10 },
  insightTitle: { color: '#FFE082', fontWeight: '700', marginBottom: 4 },
  insightBody: { color: '#F2F5FF', fontSize: 12, lineHeight: 18 },
  mapPlaceholder: { borderRadius: 14, borderWidth: 1, borderColor: 'rgba(129,199,132,0.5)', backgroundColor: 'rgba(129,199,132,0.12)', padding: 16, marginBottom: 10 },
  mapText: { color: '#E8F5E9', fontSize: 16, fontWeight: '600' },
  mapSubtext: { color: '#C8D8EC', marginTop: 8, fontSize: 12 },
});
